### ISSUE TITLE
Transpilering

### ISSUE THREAD

**Issue by helgefredheim** [storbukas/norsk-validator#4]
Er det aktuelt å publisere denne pakken i en ferdig transpilert versjon?

**Comment by roffelsaurus** [comment]
I also needed this and found a bug in fodselsnummer(ssn), so decided to do a cheeky off-site fork of this package to get ts, babel and english language: https://github.com/ssfbank/norwegian-id-validators

**Comment by storbukas** [comment]
Hei @helgefredheim, beklager sent svar, vil du se på PR om det ser greit ut? https://github.com/storbukas/norsk-validator/pull/5

**Comment by storbukas** [comment]
@roffelsaurus cool! I might convert to typescript as well 😄could you please elaborate on which bug you found?

**Comment by roffelsaurus** [comment]
Hey,

yeah, fodselsnummer weighted sum should be zero-indexed:

https://github.com/storbukas/norsk-validator/blob/fb08ea3efc4be5b886abe1ca82f35f299dca070e/src/fodselsnummer.js#L10

You just got lucky with test cases. Most, including mine will not pass.

**Comment by storbukas** [comment]
Ah, of course! Yes, both of my tests for validity on fødselsnummer has 0 as first number. I'll add a fix for that, and add some more test cases. Thank you 👍
